# Generated by Django 3.2.12 on 2022-05-20 13:00

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', markupfield.fields.MarkupField(null=True, rendered_field=True)),
                ('comment_markup_type', models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default='html', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_comment_rendered', models.TextField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upvote', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body', markupfield.fields.MarkupField(null=True, rendered_field=True)),
                ('body_markup_type', models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default='html', max_length=30)),
                ('is_question', models.BooleanField(default=False)),
                ('_body_rendered', models.TextField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagging', models.JSONField(default=list)),
                ('upvote', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
