# Generated by Django 3.2.12 on 2022-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20220519_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default='plain', max_length=30),
        ),
    ]
